version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./airflow/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  airflow:
    build:
      context: .
      dockerfile: DockerFile
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW_LOAD_EXAMPLES}
      AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
      #AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_SQL_ALCHEMY_CONN}
    volumes:
      - ./airflow:/opt/airflow
      - ./airflow:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/shared:/opt/airflow/shared
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: standalone

volumes:
  pgdata:

